/** Tool names reserved for Ashy migrations from n8n. */
export const TOOL_NAMES = Object.freeze([
	'get_sales',
	'get_expenses',
	'get_stock',
	'get_products',
	'get_debts',
	'create_sale',
	'create_expense',
	'update_sale',
	'update_expense',
	'adjust_stock',
	'generate_report',
]);

const BASE_SCHEMA = {
	type: 'object',
	additionalProperties: false,
};

export const TOOL_METADATA = {
	get_sales: {
		name: 'get_sales',
		description: 'Read authenticated sales from Supabase public.ventes',
		access: 'read',
		implemented: true,
		requiresConfirmation: false,
		mutatesData: false,
		sourceOfTruth: 'supabase',
		inputSchema: {
			...BASE_SCHEMA,
			properties: {
				period: { type: 'string' },
				startDate: { type: 'string' },
				endDate: { type: 'string' },
				product: { type: 'string' },
				limit: { type: 'number' },
				order: { type: 'string', enum: ['date_desc', 'date_asc'] },
			},
		},
	},
	get_expenses: {
		name: 'get_expenses',
		description: 'Read authenticated expenses from Supabase public.depenses',
		access: 'read',
		implemented: true,
		requiresConfirmation: false,
		mutatesData: false,
		sourceOfTruth: 'supabase',
		inputSchema: {
			...BASE_SCHEMA,
			properties: {
				period: { type: 'string' },
				startDate: { type: 'string' },
				endDate: { type: 'string' },
				category: { type: 'string' },
				limit: { type: 'number' },
				order: { type: 'string', enum: ['date_desc', 'date_asc'] },
			},
		},
	},
	get_stock: {
		name: 'get_stock',
		description: 'Read authenticated stock levels from Supabase public.stocks',
		access: 'read',
		implemented: true,
		requiresConfirmation: false,
		mutatesData: false,
		sourceOfTruth: 'supabase',
		inputSchema: {
			...BASE_SCHEMA,
			properties: {
				product: { type: 'string' },
				lowStockOnly: { type: 'boolean' },
				limit: { type: 'number' },
			},
		},
	},
	get_products: {
		name: 'get_products',
		description: 'Read authenticated product catalogue from Supabase public.produits',
		access: 'read',
		implemented: true,
		requiresConfirmation: false,
		mutatesData: false,
		sourceOfTruth: 'supabase',
		inputSchema: {
			...BASE_SCHEMA,
			properties: {
				product: { type: 'string' },
				category: { type: 'string' },
				limit: { type: 'number' },
				order: {
					type: 'string',
					enum: ['name_asc', 'name_desc', 'created_desc', 'created_asc'],
				},
			},
		},
	},
	get_debts: {
		name: 'get_debts',
		description: 'Read authenticated client debts from Supabase public.ventes (reste_a_payer)',
		access: 'read',
		implemented: true,
		requiresConfirmation: false,
		mutatesData: false,
		sourceOfTruth: 'supabase',
		inputSchema: {
			...BASE_SCHEMA,
			properties: {
				period: { type: 'string' },
				startDate: { type: 'string' },
				endDate: { type: 'string' },
				status: { type: 'string', enum: ['unpaid', 'settled', 'all'] },
				debtor: { type: 'string' },
				limit: { type: 'number' },
				order: { type: 'string', enum: ['date_desc', 'date_asc'] },
			},
		},
	},
	create_sale: {
		name: 'create_sale',
		description: 'Create a sale in Supabase after validation',
		access: 'write',
		implemented: false,
		requiresConfirmation: true,
		mutatesData: true,
		sourceOfTruth: 'supabase',
		inputSchema: BASE_SCHEMA,
	},
	create_expense: {
		name: 'create_expense',
		description: 'Create an expense in Supabase after validation',
		access: 'write',
		implemented: false,
		requiresConfirmation: true,
		mutatesData: true,
		sourceOfTruth: 'supabase',
		inputSchema: BASE_SCHEMA,
	},
	update_sale: {
		name: 'update_sale',
		description: 'Update an existing sale in Supabase',
		access: 'write',
		implemented: false,
		requiresConfirmation: true,
		mutatesData: true,
		sourceOfTruth: 'supabase',
		inputSchema: BASE_SCHEMA,
	},
	update_expense: {
		name: 'update_expense',
		description: 'Update an existing expense in Supabase',
		access: 'write',
		implemented: false,
		requiresConfirmation: true,
		mutatesData: true,
		sourceOfTruth: 'supabase',
		inputSchema: BASE_SCHEMA,
	},
	adjust_stock: {
		name: 'adjust_stock',
		description: 'Adjust stock in Supabase after validation',
		access: 'write',
		implemented: false,
		requiresConfirmation: true,
		mutatesData: true,
		sourceOfTruth: 'supabase',
		inputSchema: BASE_SCHEMA,
	},
	generate_report: {
		name: 'generate_report',
		description: 'Generate a report from Supabase-backed data',
		access: 'read',
		implemented: false,
		requiresConfirmation: false,
		mutatesData: false,
		sourceOfTruth: 'supabase',
		inputSchema: BASE_SCHEMA,
	},
};

export const TOOL_DEFINITIONS = TOOL_NAMES.map((name) => TOOL_METADATA[name]);
